const indianColleges = [
  {
    id: 1,
    cdRank: 1,
    name: "Indian Institute of Science (IISc) Bangalore",
    location: "Bangalore, Karnataka, India",
    courseFees: 15000,
    placement: 3500000,
    userReviews: 8.8,
    ranking: "#1st/500 in India"
  },
  {
    id: 2,
    cdRank: 2,
    name: "IIT Madras - Indian Institute of Technology [IITM], Chennai",
    location: "Chennai, Tamil Nadu",
    courseFees: 209550,
    placement: 2148000,
    userReviews: 8.6,
    ranking: "#3rd/141 in India",
    featured: true
  },
  {
    id: 3,
    cdRank: 3,
    name: "IIT Delhi - Indian Institute of Technology [IITD], New Delhi",
    location: "New Delhi, Delhi NCR",
    courseFees: 254650,
    placement: 2582000,
    userReviews: 8.7,
    ranking: "#1st/35 in India",
    featured: true
  },
  {
    id: 4,
    cdRank: 4,
    name: "IIT Bombay - Indian Institute of Technology [IITB], Mumbai",
    location: "Mumbai, Maharashtra",
    courseFees: 225000,
    placement: 2200000,
    userReviews: 8.9,
    ranking: "#2nd/35 in India",
    featured: true
  },
  {
    id: 5,
    cdRank: 5,
    name: "IIT Kanpur - Indian Institute of Technology [IITK], Kanpur",
    location: "Kanpur, Uttar Pradesh",
    courseFees: 200000,
    placement: 2000000,
    userReviews: 8.7,
    ranking: "#4th/35 in India",featured: true
  },
  {
    id: 6,
    cdRank: 6,
    name: "IIT Kharagpur - Indian Institute of Technology [IITKGP], Kharagpur",
    location: "Kharagpur, West Bengal",
    courseFees: 190000,
    placement: 1800000,
    userReviews: 8.8,
    ranking: "#5th/35 in India",
  },
  {
    id: 7,
    cdRank: 7,
    name: "IIT Roorkee - Indian Institute of Technology [IITR], Roorkee",
    location: "Roorkee, Uttarakhand",
    courseFees: 210000,
    placement: 1700000,
    userReviews: 8.6,
    ranking: "#6th/35 in India",featured: true
  },
  {
    id: 8,
    cdRank: 8,
    name: "IIT Guwahati - Indian Institute of Technology [IITG], Guwahati",
    location: "Guwahati, Assam",
    courseFees: 200000,
    placement: 1600000,
    userReviews: 8.7,
    ranking: "#7th/35 in India",
    featured: true
  },
  {
    id: 9,
    cdRank: 9,
    name: "IIT Hyderabad - Indian Institute of Technology [IITH], Hyderabad",
    location: "Hyderabad, Telangana",
    courseFees: 210000,
    placement: 1500000,
    userReviews: 8.5,
    ranking: "#8th/35 in India",
  },
  {
    id: 10,
    cdRank: 10,
    name: "NIT Trichy - National Institute of Technology [NITT], Tiruchirappalli",
    location: "Tiruchirappalli, Tamil Nadu",
    courseFees: 140000,
    placement: 1300000,
    userReviews: 8.4,
    ranking: "#1st/31 in India",
  },
  {
    id: 11,
    cdRank: 11,
    name: "BITS Pilani - Birla Institute of Technology and Science, Pilani",
    location: "Pilani, Rajasthan",
    courseFees: 300000,
    placement: 1500000,
    userReviews: 8.7,
    ranking: "#1st/30 in India",
    featured: true
  },
  {
    id: 12,
    cdRank: 12,
    name: "IIT Indore - Indian Institute of Technology [IITI], Indore",
    location: "Indore, Madhya Pradesh",
    courseFees: 200000,
    placement: 1400000,
    userReviews: 8.5,
    ranking: "#9th/35 in India",
  },
  {
    id: 13,
    cdRank: 13,
    name: "IIT BHU - Indian Institute of Technology [IIT BHU], Varanasi",
    location: "Varanasi, Uttar Pradesh",
    courseFees: 210000,
    placement: 1450000,
    userReviews: 8.6,
    ranking: "#10th/35 in India",
  },
  {
    id: 14,
    cdRank: 14,
    name: "IIT Patna - Indian Institute of Technology [IITP], Patna",
    location: "Patna, Bihar",
    courseFees: 190000,
    placement: 1400000,
    userReviews: 8.4,
    ranking: "#11th/35 in India",
  },
  {
    id: 15,
    cdRank: 15,
    name: "IIT Ropar - Indian Institute of Technology [IITRPR], Rupnagar",
    location: "Rupnagar, Punjab",
    courseFees: 200000,
    placement: 1350000,
    userReviews: 8.5,
    ranking: "#12th/35 in India",
  },
  {
    id: 16,
    cdRank: 16,
    name: "IIT Gandhinagar - Indian Institute of Technology [IITGN], Gandhinagar",
    location: "Gandhinagar, Gujarat",
    courseFees: 210000,
    placement: 1300000,
    userReviews: 8.4,
    ranking: "#13th/35 in India",
  },
  {
    id: 17,
    cdRank: 17,
    name: "IIT Bhubaneswar - Indian Institute of Technology [IITBBS], Bhubaneswar",
    location: "Bhubaneswar, Odisha",
    courseFees: 200000,
    placement: 1250000,
    userReviews: 8.3,
    ranking: "#14th/35 in India",
  },
  {
    id: 18,
    cdRank: 18,
    name: "IIT Jodhpur - Indian Institute of Technology [IITJ], Jodhpur",
    location: "Jodhpur, Rajasthan",
    courseFees: 200000,
    placement: 1200000,
    userReviews: 8.3,
    ranking: "#15th/35 in India",
  },
  {
    id: 19,
    cdRank: 19,
    name: "IIT Mandi - Indian Institute of Technology [IITMandi], Mandi",
    location: "Mandi, Himachal Pradesh",
    courseFees: 200000,
    placement: 1250000,
    userReviews: 8.2,
    ranking: "#16th/35 in India",
  },
  {
    id: 20,
    cdRank: 20,
    name: "IIIT Hyderabad - International Institute of Information Technology [IIITH], Hyderabad",
    location: "Hyderabad, Telangana",
    courseFees: 300000,
    placement: 1400000,
    userReviews: 8.6,
    ranking: "#1st/25 in India",
  }
];

module.exports = indianColleges;
